// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact           = require("reason-react/lib/js/src/reasonReact.js");
var ReactNativeRouterFlux = require("react-native-router-flux");

function make(children) {
  return ReasonReact.wrapJsForReason(ReactNativeRouterFlux.Router, { }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
