// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact                                                                      = require("reason-react/lib/js/src/reasonReact.js");
var $dot$dot$slash$dot$dot$slash$dot$dot$slash$dot$dot$slashsrc$slashrnrf$slashScene = require("../../../../src/rnrf/Scene");

function make(name, component, title, children) {
  return ReasonReact.wrapJsForReason($dot$dot$slash$dot$dot$slash$dot$dot$slash$dot$dot$slashsrc$slashrnrf$slashScene.default, {
              name: name,
              component: component,
              title: title
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
