// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact                                                                      = require("reason-react/lib/js/src/reasonReact.js");
var $dot$dot$slash$dot$dot$slash$dot$dot$slash$dot$dot$slashsrc$slashrnrf$slashStack = require("../../../../src/rnrf/Stack");

function make(name, children) {
  return ReasonReact.wrapJsForReason($dot$dot$slash$dot$dot$slash$dot$dot$slash$dot$dot$slashsrc$slashrnrf$slashStack.default, {
              name: name
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
